In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# 単純なアレイを用意します。
arr1 = np.arange(9).reshape((3,3))

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1 = Series([0,1,2], index=['T', 'U', 'V'])
ser2 = Series([3,4], index=['X','Y'])

In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [14]:
pd.concat([ser1,ser2],axis=1, keys=['cat1', 'cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [15]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
dframe1

X         Y         Z
0  0.009259  1.312037 -0.755534
1 -0.771676 -0.658053  1.888816
2 -0.260731  1.273933 -0.177242
3  0.303129 -1.419642  0.109271

In [16]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])
dframe2

Y         Q         X
0 -1.525909  0.909067  0.846670
1  0.019630 -0.175046  1.101861
2 -0.220446  1.021646  0.442766

In [17]:
pd.concat([dframe1, dframe2])

X         Y         Z         Q
0  0.009259  1.312037 -0.755534       NaN
1 -0.771676 -0.658053  1.888816       NaN
2 -0.260731  1.273933 -0.177242       NaN
3  0.303129 -1.419642  0.109271       NaN
0  0.846670 -1.525909       NaN  0.909067
1  1.101861  0.019630       NaN -0.175046
2  0.442766 -0.220446       NaN  1.021646

In [18]:
pd.concat([dframe1, dframe2], ignore_index=True)

X         Y         Z         Q
0  0.009259  1.312037 -0.755534       NaN
1 -0.771676 -0.658053  1.888816       NaN
2 -0.260731  1.273933 -0.177242       NaN
3  0.303129 -1.419642  0.109271       NaN
4  0.846670 -1.525909       NaN  0.909067
5  1.101861  0.019630       NaN -0.175046
6  0.442766 -0.220446       NaN  1.021646