# アレイの添え字

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# 添え字を使ったアクセス
arr[8]

8

In [5]:
# １から５の手前まで
arr[1:5]

array([1, 2, 3, 4])

In [7]:
# スライスは参照が返ってくるので、同時に導入出来ます。
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# reset
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
# スライスを変更（すべての要素）
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### sliceした部分の変更は元の配列にも反映される
### copyしたarrayの変更は反映されない

In [13]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy[:] = 50
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
# 2次元アレイの添え字
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
# 行を取り出す。
arr_2d[1]

array([20, 25, 30])

In [18]:
# 行、列を指定して取り出す。
arr_2d[1][2]

30

In [19]:
# １行目まで、１列目から
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr_length = arr2d.shape[1]
arr_length

10

### shape
```
☑︎shape
a = np.array([[1,2,3],[4,5,6]])
a.shape
>>>(2, 3)　arrayの行、列を表示
a.shape[0]
>>>2　行を表示
a.shape[1]
>>>3　列を表示

```

In [30]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

### 行の取り出し

In [31]:
# 偶数行だけを取り出す便利な添え字
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [32]:
# 入れ替え可
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])