# numpy

In [1]:
# Numpyのアレイを利用
import numpy as np

# Pythonのリスト型から変換して作ることができる。
my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [36]:
# 別のアレイを作って
my_list2 = [11,22,33,44]

# リストのリストを作成、多次元配列
my_lists = [my_list1,my_list2]

# これを使って、多次元のアレイを作れる
my_array2 = np.array(my_lists)

my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

### shape dtype は（）付かない。何行、何列。

In [11]:
#アレイのサイズを調べる
my_array2.shape

(2, 4)

In [12]:
# アレイの型を調べる
my_array2.dtype

dtype('int64')

### numpy arrayはpythonと違い全て同じ型出ないといけない

In [13]:
# 全ての要素が０
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
my_zeros_array = np.zeros(5)

In [24]:
my_zeros_array.dtype

dtype('float64')

In [37]:
# 全ての要素が１
np.ones((5,5))

TypeError: 'tuple' object is not callable

In [29]:
# 全ての要素が空、０ではない
np.empty(5)
np.empty((3,4))

array([[2.e+000, 2.e+000, 4.e-323, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000, 0.e+000]])

In [31]:
#単位行列I（dentity array）
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### arange関数

In [33]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [34]:
# 最初と最後を決めて何個ずつ飛ばすか
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])