# アレイと計算のための関数

In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# 平方根
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
# 自然対数の底ｅの累乗
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
# 正規分布に従う乱数
A = np.random.randn(10)
A

array([ 0.89067485,  0.85470566,  0.50127894, -0.69885935,  1.21899081,
        2.04821408,  1.28372606, -0.62044197, -1.07967901,  1.48868242])

In [8]:
B = np.random.randn(10)
B

array([-1.27850724,  0.58028367,  1.81755713,  1.2933612 , -1.98369278,
       -0.24375971, -0.96926278,  0.61099068, -0.02274442, -0.39948799])

In [9]:
# 2つのアレイを足す
np.add(A,B)

array([-0.38783239,  1.43498933,  2.31883607,  0.59450184, -0.76470196,
        1.80445437,  0.31446328, -0.00945128, -1.10242342,  1.08919443])

In [10]:
# 各要素の大きいほうを返す
np.maximum(A,B)

array([ 0.89067485,  0.85470566,  1.81755713,  1.2933612 ,  1.21899081,
        2.04821408,  1.28372606,  0.61099068, -0.02274442,  1.48868242])