# アレイの入出力

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
#バイナリデータとして保存 (拡張子は .npy)
np.save('my_array',arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1 = np.load('my_array.npy')
arr2 = np.arange(10)

In [10]:
arr1

array([0, 1, 2, 3, 4])

In [11]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#複数のアレイをzip形式で保存
np.savez('ziparrays.npz',x=arr1,y=arr2)

In [13]:
# ディスクから読み込む
archive_array = np.load('ziparrays.npz')
archive_array['x']

array([0, 1, 2, 3, 4])

In [14]:
arr =np.array([[1,2,3,4],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [15]:
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [16]:
!cat my_test_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00


In [17]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])